"""empty message

Revision ID: 728180af9d04
Revises: 
Create Date: 2023-10-05 01:37:13.355067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '728180af9d04'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokenblockedlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=250), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('url_perfil', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_evento', sa.String(length=50), nullable=False),
    sa.Column('descr_corta', sa.String(length=100), nullable=False),
    sa.Column('fecha_ini', sa.String(length=50), nullable=False),
    sa.Column('fecha_fin', sa.String(length=50), nullable=False),
    sa.Column('ubicacion', sa.String(length=100), nullable=False),
    sa.Column('logotipo', sa.String(length=150), nullable=False),
    sa.Column('descr_larga', sa.String(length=250), nullable=False),
    sa.Column('reglas', sa.String(length=150), nullable=False),
    sa.Column('fecha_lim', sa.String(length=50), nullable=False),
    sa.Column('hora_lim', sa.String(length=10), nullable=False),
    sa.Column('email_contacto', sa.String(length=50), nullable=False),
    sa.Column('tel_contacto', sa.String(length=15), nullable=False),
    sa.Column('nombre_contacto', sa.String(length=150), nullable=False),
    sa.Column('costo', sa.Float(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cant_equipos', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('cant_registrados', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_equipo', sa.String(length=50), nullable=False),
    sa.Column('jugadores', sa.String(length=100), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.Column('logotipo', sa.String(length=150), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_equipo')
    )
    op.create_table('events_pagos',
    sa.Column('events_id', sa.Integer(), nullable=False),
    sa.Column('pagos_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['events_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['pagos_id'], ['pagos.id'], ),
    sa.PrimaryKeyConstraint('events_id', 'pagos_id')
    )
    op.create_table('events_registros',
    sa.Column('events_id', sa.Integer(), nullable=False),
    sa.Column('registros_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['events_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['registros_id'], ['registros.id'], ),
    sa.PrimaryKeyConstraint('events_id', 'registros_id')
    )
    op.create_table('teams_registros',
    sa.Column('teams_id', sa.Integer(), nullable=False),
    sa.Column('registros_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['registros_id'], ['registros.id'], ),
    sa.ForeignKeyConstraint(['teams_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('teams_id', 'registros_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teams_registros')
    op.drop_table('events_registros')
    op.drop_table('events_pagos')
    op.drop_table('teams')
    op.drop_table('registros')
    op.drop_table('pagos')
    op.drop_table('events')
    op.drop_table('user')
    op.drop_table('tokenblockedlist')
    # ### end Alembic commands ###
